
  spring:
    application:
      name: atlas-logistics
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
    elasticsearch:
      uris: ${SPRING_ELASTIC_URIS}
    jpa:
      hibernate:
        ddl-auto: none
    flyway:
      baseline-on-migrate: true
    springdoc:
      hateoas:
        enabled: true
      show-actuator: true
      api-docs:
        path: /api-docs
        resolve-external-entities: true
      swagger-ui:
        path: /swagger-ui.html
    messages:
      basename: messages
      encoding: UTF-8




  server:
    servlet:
      session:
        timeout: 60m
      encoding:
        force-response: true
        charset: UTF-8

  my:
    app:
      secret: rRMdgFTf2xneIM1WBiD8u1iMGmTruAL706vKfbJtKTInFKJsIenTPnmODlRwxD5v
